name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --shamefully-hoist
      - run: pnpm run generate

      - uses: actions/upload-artifact@v3
        with:
          name: m4rc3l.de
          path: .output/public
